package utils;

public enum RoomAmenity {
	FREE_TOILETRIES,HAIR_DRYER,TOILET,TOILET_PAPER,BATH_OR_SHOWER,DESK,FLAT_SCREEN_TV,WAKEUP_SERVICE_ALARM_CLOCK,SOFA,IRON,TOWELS,SOCKETS,REFRIDGERATOR,LINEN,ELECTRIC_KETTLE,AIR_CONDITIONING_FOR_ROOM,HEATING,CABLE_CHANNELS,WARDROBE_CLOSET,MOSQUITO_NET,KITCHENETTE,SOFA_BED,INTER_CONNECTED_ROOMS_AVAILABLE,SEATING_AREA;
}
